### ISSUE TITLE
Centered embeds are not centered correctly

### ISSUE THREAD

**Issue by MatzeKitt** [epiphyt/embed-privacy#66]
See: https://wordpress.org/support/topic/youtube-not-centered/

Adding this CSS should do the work:

```css
.aligncenter .embed-privacy-content > * {
	display: block;
	margin-left: auto;
	margin-right: auto;
}
```
